services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - "./backend:/usr/src/app"
      - backend_node_modules:/usr/src/app/node_modules
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
    restart: on-failure
    mem_limit: 1.5g
    user: "1100:1100"

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    mem_limit: 1.5g
    user: "1000:1000"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:8080"
    volumes:
      - "./frontend:/app"
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    mem_limit: 1.5g
    user: "1200:1200"

volumes:
  pgdata:
  backend_node_modules:
  frontend_node_modules: