-- AlterTable
ALTER TABLE "User" ADD COLUMN     "elo" INTEGER NOT NULL DEFAULT 600,
ADD COLUMN     "isBad" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "isInGame" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "isInQueue" BOOLEAN NOT NULL DEFAULT false;
